language: node_js
dist: xenial
addons:
  chrome: stable
notifications:
  email: false
cache:
  directories:
    - node_modules
sudo: required
node_js:
  - "10.15.3"
services:
  - xvfb
env:
  global:
    - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
# allow headful tests
before_install:
  # Enable user namespace cloning
  - "sysctl kernel.unprivileged_userns_clone=1"
install:
  - npm i
script:
  - npm run test:integration